version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/icyflame/year-in-twitter
    steps:
      - checkout
      - run: git clone git@github.com:icyflame/gospec.git
      - run: go get -v -t -d ./...
      - run: ./gospec
